-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVmP/QU/0Qu3JLGaH
4urSwkQ9x9SElpZjo8wNfYIMpzqgCgYIKoZIzj0DAQehRANCAAQtiUXT5PYjfMDK
WvHUUw+2AvzVrUX9lIqugyEHcFbDrMCLlIO5wHPHG6a3BiWUyERfjIaj0n446XPJ
48Vwn/8d
-----END PRIVATE KEY-----
